name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0
      
    - name: Get previous tag
      id: get_previous_tag
      run: |
        echo "PREV_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))">>$GITHUB_ENV
        echo "CURR_TAG=$(git describe --abbrev=0 --tags)">>$GITHUB_ENV

    - name: Generate changelog
      id: generate_changelog
      run: |
        echo "Previous tag: $PREV_TAG"
        echo "Current tag: $CURR_TAG"
        FULL_CHANGELOG="**Full Changelog**: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/compare/$PREV_TAG...$CURR_TAG"
        COMMITS=$(git log $PREV_TAG..HEAD --pretty=format:"%h %s (%an, %ar)")
        {
          echo 'changelog<<EOF'
          echo -e "$COMMITS\n\n$FULL_CHANGELOG"
          echo EOF
        } >> $GITHUB_OUTPUT

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # 或你项目的 Node.js 版本

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: publish release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./list-viewer.zip
        # bodyFile: "body.md"
        # generateReleaseNotes: true
        body: ${{ steps.generate_changelog.outputs.changelog }}
        makeLatest: latest
        tag: latest
        token: ${{ secrets.GITHUB_TOKEN }}
